version: "2"

services:
  tomcat:
    image: tomcat:8.0-jre8
    restart: always
    ports:
        - 8090:8080
        - 8091:8081
    volumes:
        - ./web01:/usr/local/tomcat/web01
        - ./web02:/usr/local/tomcat/web02
        - ./conf/server.xml:/usr/local/tomcat/conf/server.xml
    links:
        - api


  api:
    image: tomcat-api:0.1
    restart: always
    links:
       - mysql


  mysql:
    image: docker.io/mysql:5.6
    restart: always
    volumes:
      - ./mysql/:/var/lib/mysql/
      - ./conf/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root


         
